### ISSUE TITLE
How does setup work?

### ISSUE THREAD

**Issue by Particpant** [kjoconnor/ha-hatch-baby-rest#1]
I tried setting up the integration, but it just spins and says "No devices found". Will the integration pick up the Hatch via BT discovery, or do I need to do something specific either on the hatch itself or in HA?

Thanks for pointing me at this integration, btw.

**Comment by Particpant** [comment]
Several hours later, the device was detected by autodiscovery. Manual flow may be busted.

**Comment by kjoconnor** [comment]
Auto discovery worked for me fairly quickly, through a BTLE proxy running ESPHome. I am not really sure why it works for some and doesn't work for others, between the Hatch and HA it's tough to know where some of the problems lie.

I'll welcome PRs for addressing manual flow issues but I won't be fixing it myself. Thanks for reporting.

**Comment by Particpant** [comment]
"known broken" is fine by me, thanks!
